import type { NextPage } from 'next'
import Head from 'next/head'
import LoginForm from '../components/LoginForm'
import Navbar from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Web App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <LoginForm />
    </div>
  )
}

export default Home
